// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7nnmh-PaNjQnSP1pLQvzlIvZ20CsCtew',
    appId: '1:444805055193:web:fd69f3daacc2e3ae0eb4c8',
    messagingSenderId: '444805055193',
    projectId: 'crudoperation-dcf9e',
    authDomain: 'crudoperation-dcf9e.firebaseapp.com',
    storageBucket: 'crudoperation-dcf9e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzxBUlvxC1i9GdS9d-PkX0eXE6E922-eM',
    appId: '1:444805055193:android:bcd2a83b9323eb3e0eb4c8',
    messagingSenderId: '444805055193',
    projectId: 'crudoperation-dcf9e',
    storageBucket: 'crudoperation-dcf9e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc_lvVM1s_51lxF6Z0O6_EmC5Wjm4hm_s',
    appId: '1:444805055193:ios:03f642f9c762eecd0eb4c8',
    messagingSenderId: '444805055193',
    projectId: 'crudoperation-dcf9e',
    storageBucket: 'crudoperation-dcf9e.appspot.com',
    iosBundleId: 'com.kwame.crudWithFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc_lvVM1s_51lxF6Z0O6_EmC5Wjm4hm_s',
    appId: '1:444805055193:ios:d7db61984d1e24520eb4c8',
    messagingSenderId: '444805055193',
    projectId: 'crudoperation-dcf9e',
    storageBucket: 'crudoperation-dcf9e.appspot.com',
    iosBundleId: 'com.kwame.crudWithFirebase.RunnerTests',
  );
}
